### ISSUE TITLE
.tsk export

### ISSUE THREAD

**Issue by borisrorsvort** [xp-soaring/b21_task_planner#1]
Would it be possible to convert the flight plan as a tsk file so we can import it in xcsoar?

**Comment by ijl20** [comment]
I'll have a look at it. Help me out by giving me any links to the documentation for the XCSoar .tsk format. Also if .tsk <-> .pln files are converted in other software a link would be useful too.

**Comment by borisrorsvort** [comment]
There is a software that does it already, so you could have a look at the output http://www.ukvga.org/downloads/Turnpoints/MakeRacingTask.zip

The tsk is not documented sadly (https://github.com/XCSoar/XCSoar/issues/542#issuecomment-796830059) but that thread might help
